// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {protocol} from '../models';

export function GetApplicationEvents(arg1:string,arg2:number):Promise<Array<database.AppEvent>>;

export function GetOverview():Promise<protocol.Overview>;

export function GetSyncRun(arg1:string):Promise<database.SyncRun>;

export function ListApplications():Promise<Array<database.ManagedAppState>>;

export function TriggerSync(arg1:string):Promise<database.SyncRun>;
