// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApplicationEvents(arg1, arg2) {
  return window['go']['main']['UIBackend']['GetApplicationEvents'](arg1, arg2);
}

export function GetOverview() {
  return window['go']['main']['UIBackend']['GetOverview']();
}

export function GetSyncRun(arg1) {
  return window['go']['main']['UIBackend']['GetSyncRun'](arg1);
}

export function ListApplications() {
  return window['go']['main']['UIBackend']['ListApplications']();
}

export function TriggerSync(arg1) {
  return window['go']['main']['UIBackend']['TriggerSync'](arg1);
}
