# Simple Makefile for a Go project
build:
	@echo "Building..."
	@go build -o bin/fleetctrl-client.exe ./cmd/main
	@cd cmd/ui && go run github.com/wailsapp/wails/v2/cmd/wails@v2.13.0 build -clean -platform windows/amd64 -webview2 download -o fleetctrl-ui.exe
	@cp cmd/ui/build/bin/fleetctrl-ui.exe bin/fleetctrl-ui.exe

build-ui:
	@cd cmd/ui && go run github.com/wailsapp/wails/v2/cmd/wails@v2.13.0 build -clean -platform windows/amd64 -webview2 download -o fleetctrl-ui.exe
	@cp cmd/ui/build/bin/fleetctrl-ui.exe bin/fleetctrl-ui.exe


test:
	@echo "Running tests..."
	@go test ./...


test-v:
	@echo "Running tests (verbose)..."
	@go test -v ./...


test-cover:
	@echo "Running tests with coverage..."
	@go test ./... -coverprofile=coverage.out
	@go tool cover -func=coverage.out


test-apps:
	@echo "Running app tests..."
	@go test -v ./internal/apps/...


# Run the application
run:
	@go run cmd/main/main.go
